In [239]:
import qutip as qu
import numpy as np
import matplotlib.pyplot as plt

###### for any reference see PDF-guide from the QuTip site

# Things shown by Vodola

In [3]:
#define the second ('1') basis vector of an Hilbert space of dimension 3 (as a column (ket) vector)

basis (3,1)

Quantum object: dims = [[3], [1]], shape = (3, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]]

In [4]:
#define the first ('1') basis vector of an Hilbert space of dimension 2 (as a row (bra) vector)

basis (2,0).dag()

Quantum object: dims = [[1], [2]], shape = (1, 2), type = bra
Qobj data =
[[1. 0.]]

In [5]:
#tensorial product 

tensor(basis(3,2),basis(3,0))

Quantum object: dims = [[3, 3], [1, 1]], shape = (9, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]]

In [6]:
tensor(basis(3,2),basis(3,0).dag())

Quantum object: dims = [[3, 1], [1, 3]], shape = (3, 3), type = oper, isherm = False
Qobj data =
[[0. 0. 0.]
 [0. 0. 0.]
 [1. 0. 0.]]

In [12]:
tensor(basis(2,0),basis(3,0))


Quantum object: dims = [[2, 3], [1, 1]], shape = (6, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]

In [13]:
tensor(basis(6,0))

Quantum object: dims = [[6], [1]], shape = (6, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]

In [14]:
tensor(basis(2,0),basis(3,0)) + tensor(basis(6,0))

TypeError: Incompatible quantum object dimensions

In [15]:
tensor(sigmaz(),sigmaz(), qeye(2))

Quantum object: dims = [[2, 2, 2], [2, 2, 2]], shape = (8, 8), type = oper, isherm = True
Qobj data =
[[ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.]]

In [16]:
tensor(sigmaz(), qeye(2))

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  0.  0. -1.]]

In [17]:
tensor( qeye(2), sigmaz())

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 1.  0.  0.  0.]
 [ 0. -1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0. -1.]]

In [23]:
Z = 1j*sigmaz()

In [24]:
Z.expm()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[0.54030231+0.84147098j 0.        +0.j        ]
 [0.        +0.j         0.54030231-0.84147098j]]

In [25]:
(1j*sigmaz()).expm()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[0.54030231+0.84147098j 0.        +0.j        ]
 [0.        +0.j         0.54030231-0.84147098j]]

In [26]:
(1j*sigmax()).expm()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[0.54030231+0.j         0.        +0.84147098j]
 [0.        +0.84147098j 0.54030231+0.j        ]]

# Introduction from QuTip guide

## quantum objects (vectors and operators) class: Qobj()


Ways to **define a quantum state**:

In [10]:
Qobj([[0],[1]])

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]

In [11]:
a = np.array([0,1])
Qobj(a)

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]

In [12]:
ket('1')

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]

In [13]:
basis(2,1)

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]

In [8]:
# ket (0,1)
x = Qobj([[0],[1]])

In [9]:
x

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]

In [13]:
# bra (0,1)
y = Qobj([[0,1]])

In [14]:
# ket*bra (matrix)
x*y 

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 0.]
 [0. 1.]]

In [15]:
# bra*ket (scalar)
y*x

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[1.]]

In [16]:
a = np.array([[0,0,1,0]])

In [17]:
Qobj(a)

Quantum object: dims = [[1], [4]], shape = (1, 4), type = bra
Qobj data =
[[0. 0. 1. 0.]]

In [19]:
Qobj(a).dag()

Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [1.]
 [0.]]

## predefined states

In [20]:
# N-dimensional Fock state ket vector 
basis(2,1) # or fock(2,1)

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]

In [21]:
# N-dimensional Fock density matrix (outer product of basis)
fock_dm(2,1) # here there's not the anologus basis_dm(2,1)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 0.]
 [0. 1.]]

## predefined operators

In [27]:
#Identity on a N-dimensinal space
qeye(2)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 1.]]

In [22]:
#Pauli matricies
sigmaz()
sigmax()
sigmay()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.+0.j 0.-1.j]
 [0.+1.j 0.+0.j]]

In [25]:
#plus and minus operators
sigmap()
sigmam()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[0. 0.]
 [1. 0.]]

In [54]:
#commutator/anticommutator (kind = 'normal', 'anti')
commutator(sigmaz(),sigmaz(),'normal')

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 0.]
 [0. 0.]]

In [30]:
commutator(sigmaz(),sigmax(),'normal') (in this specific example is i2sigmay())

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[ 0.  2.]
 [-2.  0.]]

destruction and creation operators: $\hat{a}^{\dagger}, \hat{a}$

In [4]:
destroy(3)

Quantum object: dims = [[3], [3]], shape = (3, 3), type = oper, isherm = False
Qobj data =
[[0.         1.         0.        ]
 [0.         0.         1.41421356]
 [0.         0.         0.        ]]

In [5]:
destroy(2)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[0. 1.]
 [0. 0.]]

In [2]:
create(2)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[0. 0.]
 [1. 0.]]

In [3]:
create(3)

Quantum object: dims = [[3], [3]], shape = (3, 3), type = oper, isherm = False
Qobj data =
[[0.         0.         0.        ]
 [1.         0.         0.        ]
 [0.         1.41421356 0.        ]]

In [4]:
#define plus and minus states (X-eigenvectors)
x1 = (basis(2,0) + basis(2,1)).unit()
x1

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.70710678]
 [0.70710678]]

## Qobj() attributes

In [34]:
#for any Qobj() (vector state or operator) it's attributes can be checked via
q = fock_dm(2,0)

In [35]:
q

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 0.]]

In [36]:
# Matrix representing state or operator
q.data

<2x2 sparse matrix of type '<class 'numpy.complex128'>'
	with 1 stored elements in Compressed Sparse Row format>

In [37]:
# List keeping track of shapes for individual components of a multipartite system (for tensor products and partial traces).
q.dims

[[2], [2]]

In [38]:
# Dimensions of underlying data matrix.
q.shape

(2, 2)

In [39]:
# Is the operator Hermitian or not?
q.isherm

True

In [40]:
# Is object of type ‘ket, ‘bra’, ‘oper’, or ‘super’?
q.type

'oper'

## operations between objects of Qobj() class

In [41]:
# operations between Qobj()

In [42]:
X = sigmax()
Y = sigmay()
Z = sigmaz()

In [43]:
X*X

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 1.]]

In [44]:
X*Z

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[ 0. -1.]
 [ 1.  0.]]

In [45]:
X+4

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[4. 1.]
 [1. 4.]]

In [46]:
X**2

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 1.]]

In [48]:
X**3

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 1.]
 [1. 0.]]

In [49]:
X/np.sqrt(2)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.         0.70710678]
 [0.70710678 0.        ]]

In [50]:
# is equal logic operator
X == X

True

In [51]:
# is not equal logic operator
X != X

False

## predefined functions operating on Qobj class

In [65]:
q = fock_dm(2,0)
a1 = basis(2,0)
a2 = basis(2,1)

In [57]:
q

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 0.]]

### functions that return informations about the object:

In [55]:
q.check_herm() # Check if quantum object is Hermitian

True

In [58]:
q.diag() # return diagonal elements

array([1., 0.])

In [73]:
Y.diag() # return diagonal elements

array([0., 0.])

In [74]:
Z.diag() # return diagonal elements

array([ 1., -1.])

In [59]:
Z.eigenstates() # return eigenstates

(array([-1.,  1.]),
 array([Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
 Qobj data =
 [[ 0.]
  [-1.]],
        Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
 Qobj data =
 [[-1.]
  [ 0.]]], dtype=object))

In [60]:
X.eigenstates()

(array([-1.,  1.]),
 array([Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
 Qobj data =
 [[-0.70710678]
  [ 0.70710678]],
        Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
 Qobj data =
 [[0.70710678]
  [0.70710678]]], dtype=object))

In [61]:
q.full() # return full (not sparse) array of q's data

array([[1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j]])

In [62]:
Z

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]]

In [63]:
Z.full()

array([[ 1.+0.j,  0.+0.j],
       [ 0.+0.j, -1.+0.j]])

In [66]:
q.matrix_element(a1.dag(),a1) #return matrix element of <bra|q|ket>

(1+0j)

In [67]:
Z.matrix_element(a1.dag(),a1) #return matrix element of <bra|q|ket>

(1+0j)

In [68]:
X.matrix_element(a1.dag(),a1) #return matrix element of <bra|q|ket>

0j

In [75]:
q.tr() #return trace of quantum object

1.0

In [76]:
Z.tr() #return trace of quantum object

0.0

In [80]:
q.ptrace(0) #return partial trace from selectect elemwnts (here sel=1) (check what does it what as argument)

TypeError: 'numpy.float64' object cannot be interpreted as an integer

In [69]:
q.norm() # return L2 norm for states (or trace norm for operators)

1.0

In [70]:
Z.norm() # return L2 norm for states (or trace norm for operators)

2.0

In [71]:
Y.norm() # return L2 norm for states (or trace norm for operators)

2.0

In [72]:
a1.norm() # return L2 norm for states (or trace norm for operators)

1.0

### functions that return modified Qobj  

In [82]:
q.unit() #return normalized vector(or operator) (q.unit = q/q.norm())

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 0.]]

In [84]:
a1.unit()

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]

In [86]:
2*a1

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[2.]
 [0.]]

In [88]:
b1 = 2*a1
b1.unit()

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]

In [93]:
q.conj() # return conjugate

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 0.]]

In [94]:
Z.conj() # return conjugate

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]]

In [95]:
Y.conj() # return conjugate

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.+0.j 0.+1.j]
 [0.-1.j 0.+0.j]]

In [96]:
q.dag() # return adjoint (dagger)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 0.]]

In [97]:
Z.dag() # return adjoint (dagger)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]]

In [107]:
Y.dag() # return adjoint (dagger)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.+0.j 0.-1.j]
 [0.+1.j 0.+0.j]]

In [98]:
a1.dag() # return adjoint (dagger)

Quantum object: dims = [[1], [2]], shape = (1, 2), type = bra
Qobj data =
[[1. 0.]]

In [99]:
q.expm() #return matrix exponential 

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[2.71828183 0.        ]
 [0.         1.        ]]

In [100]:
Z.expm() #return matrix exponential 

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[2.71828183 0.        ]
 [0.         0.36787944]]

In [101]:
X.expm() #return matrix exponential 

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1.54308063 1.17520119]
 [1.17520119 1.54308063]]

In [104]:
(3j*X).expm() #return matrix exponential 

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[-0.9899925+0.j          0.       +0.14112001j]
 [ 0.       +0.14112001j -0.9899925+0.j        ]]

In [105]:
q.trans() # transpose 

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 0.]]

In [106]:
Y.trans() # transpose 

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.+0.j 0.+1.j]
 [0.-1.j 0.+0.j]]

In [90]:
q.cosm() # return cosine of the Qobj

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.54030231 0.        ]
 [0.         1.        ]]

In [91]:
Z.cosm() # return cosine of the Qobj

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.54030231 0.        ]
 [0.         0.54030231]]

In [92]:
q.sinm() # return sine of the Qobj

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.84147098 0.        ]
 [0.         0.        ]]

In [108]:
a1.proj() # create projector from a bra or a ket

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 0.]]

### other functions for Qobj

In [110]:
expect(Z,a1) # return expectation value of operator Z for state a1

1.0

In [117]:
tensor(a1,a1) # tensor product between two vectors

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]]

#### from the isomorphis between tensor product (which gives a vector if applied to two vectors) and outer product (which gives a matrix if applied to two vectors)
#### there are functions for this conversion:

In [119]:
a1 = fock(2,0)
a2 = fock(2,1)
rho1 = fock_dm(2,0)
rho2 = fock_dm(2,1)
ten1 = tensor(a1,a1)
ten2 = tensor(a2,a2)

In [113]:
a1

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]

In [114]:
a2

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]

In [115]:
rho1

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 0.]]

In [116]:
rho2

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 0.]
 [0. 1.]]

In [120]:
ten1

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]]

In [121]:
ten2

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [1.]]

##### operator_to_vector(operator) function: 

In [122]:
operator_to_vector(rho1)

Quantum object: dims = [[[2], [2]], [1]], shape = (4, 1), type = operator-ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]]

##### vector_to_operator(vector) function:

In [123]:
vector_to_operator(ten1)

Quantum object: dims = [2, 2], shape = (2, 2), type = other
Qobj data =
[[1. 0.]
 [0. 0.]]

### I HAVE TO BE REALLY AWARE OF THIS FUNCTIONS!!!!!!! :
#### Note that QuTiP uses the column-stacking convention for the isomorphism between ℒ(ℋ) and ℋ ⊗ ℋ
#### - vector_to_operator() takes only ket as arguments (for what I've seen)
#### - operator_to_vectror() converts the vector using this convention

#### so, it's ok if I use them and
#### - for vector_to_operator(): I first apply it and then do the transpose
#### - for operator_to_vector(): I first transpose the operator and then apply the function
#### ????????
##### (see examples below)

In [154]:
tensor(H2_basis)

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]]

In [152]:
vector_to_operator(tensor(H2_basis)) #this is not how I want it to work, I have to dothe transpose of it

Quantum object: dims = [2, 2], shape = (2, 2), type = other
Qobj data =
[[0. 0.]
 [1. 0.]]

In [153]:
vector_to_operator(tensor(H2_basis)).trans() #this is the right isomophism between the tensor product (vector) and the outer product (matrix)

Quantum object: dims = [2, 2], shape = (2, 2), type = other
Qobj data =
[[0. 1.]
 [0. 0.]]

In [149]:
bra_ten1 = tensor(H2_basis).trans()
bra_ten1

Quantum object: dims = [[1, 1], [2, 2]], shape = (1, 4), type = bra
Qobj data =
[[0. 1. 0. 0.]]

In [150]:
vector_to_operator(bra_ten1)

Exception: Total size of array must be unchanged.

In [147]:
vector_to_operator(tensor(H2_basis).dag())

Exception: Total size of array must be unchanged.

## Tensor Product and partial traces (to work on more than one qubit at once: many-qbit systems): 

In [126]:
a1 = basis(2,0)
a2 = basis(2,1)
H2_basis = [a1,a2]

### Tensor product to create vectors obtained from different quatum states (i.e. which belong to different Hilbert spaces)
##### tensor() can take as arguments the vectors or a list

In [128]:
tensor(a1,a1)

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]]

In [129]:
tensor(a1,a2,a2)

Quantum object: dims = [[2, 2, 2], [1, 1, 1]], shape = (8, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]]

In [131]:
tensor(a1,basis(3,2))

Quantum object: dims = [[2, 3], [1, 1]], shape = (6, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]]

In [133]:
tensor(a1,a2)

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]]

In [132]:
tensor(H2_basis)

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]]

### Tensor product to create operators obtained from operators which act on different qubits (i.e. qubits that live in different Hilbert spaces)

In [134]:
tensor (X,Y) # tensor which acts on an Hilbert-space obtained from two qubit (2x2, dim=4), where operator X acts on qubit1 and operator Y acts on qubit2

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0.+0.j 0.+0.j 0.+0.j 0.-1.j]
 [0.+0.j 0.+0.j 0.+1.j 0.+0.j]
 [0.+0.j 0.-1.j 0.+0.j 0.+0.j]
 [0.+1.j 0.+0.j 0.+0.j 0.+0.j]]

In [135]:
tensor (qeye(2),Z) # tensor which acts on an Hilbert-space obtained from two qubit (2x2, dim=4), where operator Z acts on qubit2 (and nothing happens to qubit1)

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 1.  0.  0.  0.]
 [ 0. -1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0. -1.]]

### Partial trace to reduce dimension of an Hilbert space
##### (by eliminating some degrees of freedom by averaging (tracing). In this sense it is therefore the converse of the tensor product)

##### ptrace() take as arguments a list of the components of the system that should be kept 
##### Note that the partial trace always results in a density matrix (mixed state), regardless of whether the composite system is a pure state (described by a state vector) or a mixed state (described by a density matrix)

In [157]:
ten1 = tensor(H2_basis)
ten1

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]]

In [158]:
ten1.ptrace(0)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 0.]]

In [159]:
ten1.ptrace(1)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 0.]
 [0. 1.]]

In [140]:
outerp1 = a1*(a2.dag())
outerp1

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[0. 1.]
 [0. 0.]]

In [165]:
outerp1.ptrace(0)

TypeError: 'numpy.float64' object cannot be interpreted as an integer

In [155]:
operator_to_vector(outerp1.trans())

Quantum object: dims = [[[2], [2]], [1]], shape = (4, 1), type = operator-ket
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]]

In [162]:
vector_to_operator(ten1).trans()

Quantum object: dims = [2, 2], shape = (2, 2), type = other
Qobj data =
[[0. 1.]
 [0. 0.]]

In [166]:
vector_to_operator(ten1).trans().ptrace(0)

TypeError: 'numpy.float64' object cannot be interpreted as an integer

In [168]:
vector_to_operator(ten1).ptrace(0)

TypeError: 'numpy.float64' object cannot be interpreted as an integer

#### ptrace(list) acts only on tensors (?) 

##### here it can be seen that even if, mathematically a1*(a2.dag()) == vector_to_operator(tensor(a1,a2)).trans() (isomorphism between two vectorial spaces) for QuTip that's not the case (it also doesn't allow to do the partial trace to outerp1)

In [163]:
a1*(a2.dag()) == vector_to_operator(tensor(a1,a2)).trans() 

False

### Test to the use of operators (and tensors of operators) on states (and tensors of states)

In [169]:
a1 

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]

In [173]:
Z*a1

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]

In [174]:
Z*a2

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[ 0.]
 [-1.]]

In [175]:
X*a1

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]

In [177]:
ten1

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]]

In [178]:
XX = tensor(X,X)
XX

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]

In [179]:
XX*ten1

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [1.]]

In [180]:
tensor(X,qeye(2))*ten1

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [1.]
 [0.]]

### Make tensors of operators and vectors as list

with Hilbert space formed as a tensor product of L H2 Hilbert spaces (H2xL)

In [5]:
L = 3

In [12]:
# define up and down states (Z-eigenvectors)
z0 = basis(2,0)
z1 = basis(2,1)

# define plus and minus states (X-eigenvectors)
x0 = (basis(2,0) + basis(2,1)).unit()
x1 = (basis(2,0) - basis(2,1)).unit()

#### operators I,X,Y,Z:

In [6]:
# define I on H2xL
I = tensor([qeye(2)]*L)

steps in define list of tensors that act on an element of H2xL that on qubit i apply sigmax() and to others apply qeye(2)

1) element of the list that acts on qubit i:

In [31]:
# here we try for i = 1:
X1 = tensor([qeye(2)]*1+[sigmax()]+[qeye(2)]*(L-1-1))

test if it works:

In [32]:
X1 

Quantum object: dims = [[2, 2, 2], [2, 2, 2]], shape = (8, 8), type = oper, isherm = True
Qobj data =
[[0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]]

In [13]:
q0 = tensor(z0,z0,z0)
q3 = tensor(z1,z0,z0)

In [14]:
q0

Quantum object: dims = [[2, 2, 2], [1, 1, 1]], shape = (8, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]

#### 

In [15]:
q3

Quantum object: dims = [[2, 2, 2], [1, 1, 1]], shape = (8, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]]

In [33]:
X1*q0

Quantum object: dims = [[2, 2, 2], [1, 1, 1]], shape = (8, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]

In [34]:
X1*q3

Quantum object: dims = [[2, 2, 2], [1, 1, 1]], shape = (8, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]]

2) now that we've seen that is works fine, make the hole list:

In [35]:
X = []
for i in range(L):
    X.append(tensor([qeye(2)]*i+[sigmax()]+[qeye(2)]*(L-i-1)))

we test if it works fine:

In [36]:
X[1]

Quantum object: dims = [[2, 2, 2], [2, 2, 2]], shape = (8, 8), type = oper, isherm = True
Qobj data =
[[0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]]

In [37]:
X[1]*q0

Quantum object: dims = [[2, 2, 2], [1, 1, 1]], shape = (8, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]

#### Now we try to define general states and operators depending on L:

In [41]:
# initial state |s>:
listS = []
for i in range(L):
    listS.append(x0)
s = tensor(listS)

In [42]:
s

Quantum object: dims = [[2, 2, 2], [1, 1, 1]], shape = (8, 1), type = ket
Qobj data =
[[0.35355339]
 [0.35355339]
 [0.35355339]
 [0.35355339]
 [0.35355339]
 [0.35355339]
 [0.35355339]
 [0.35355339]]

In [3]:
F1 = np.ndarray([])

In [4]:
type(F1) 

numpy.ndarray

In [12]:
for i in range(10):
    print(np.random.randint(0,2))

1
1
1
0
1
0
1
0
1
0


In [7]:
coeffs = np.random.random(3)

In [17]:
coeffs = np.random.uniform(0,,3)

In [23]:
basis_elem = np.random.randint(0,2,3)

In [18]:
coeffs

array([0.73125561, 1.91882137, 1.68919958])

In [24]:
basis_elem

array([0, 1, 1])

In [46]:
n_qubits = 3
coeffs = np.random.random((2,n_qubits))
basis_elem = np.random.randint(0,2,(2,n_qubits))
print(coeffs)
print(basis_elem)

[[0.10002985 0.38569209 0.60853315]
 [0.27162984 0.59776162 0.03319767]]
[[1 0 1]
 [0 1 0]]


In [48]:
coeffs[0][2]

0.6085331536352261

In [267]:
n_qubits = 3
list_gen_state = []
i = 0
coeffs = np.random.random((2,n_qubits))
basis_elem = np.random.randint(0,2,(2,n_qubits))
while i < n_qubits:
    gen_qubit = (coeffs[0][i]*qu.basis(2,basis_elem[0][i]) + coeffs[1][i]*qu.basis(2,basis_elem[1][i])).unit()
    list_gen_state.append(gen_qubit)
    i += 1
gen_state = qu.tensor(list_gen_state)

In [141]:
list_gen_state

[Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
 Qobj data =
 [[0.79648081]
  [0.60466381]],
 Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
 Qobj data =
 [[0.]
  [1.]],
 Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
 Qobj data =
 [[0.99732094]
  [0.07315021]]]

In [160]:
qu.operator_to_vector(gen_state.ptrace(0))

Quantum object: dims = [[[2], [2]], [1]], shape = (4, 1), type = operator-ket
Qobj data =
[[0.63438168]
 [0.48160312]
 [0.48160312]
 [0.36561832]]

In [158]:
gen_state.ptrace(0)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.63438168 0.48160312]
 [0.48160312 0.36561832]]

In [165]:
qu.rand_ket(8,dims=[[2, 2, 2], [1, 1, 1]])

Quantum object: dims = [[2, 2, 2], [1, 1, 1]], shape = (8, 1), type = ket
Qobj data =
[[ 0.11512592-0.40189982j]
 [-0.01786588+0.08311064j]
 [ 0.23484624-0.35110154j]
 [ 0.04409172-0.31725838j]
 [-0.15404138+0.46043221j]
 [-0.06770066+0.46434966j]
 [-0.25897742-0.05166432j]
 [-0.02396861+0.10358781j]]

In [143]:
qu.tensor(list_gen_state)

Quantum object: dims = [[2, 2, 2], [1, 1, 1]], shape = (8, 1), type = ket
Qobj data =
[[0.        ]
 [0.        ]
 [0.79434699]
 [0.05826274]
 [0.        ]
 [0.        ]
 [0.60304387]
 [0.04423128]]

In [135]:
def n_sigmax(n_qubits, qubit_pos):
    """This method generates a tensor(Qobj) wich perform a single-qubit sigmax operation
       on a state of n-qubits\n
    Parameters:\n
        n_vertices: number of qubits the states is composed of\n
        qubit_pos: qubit on which the sigmax operator acts (position starts at '0')\n
    Returns:\n
        a tensor that apply sigmax on the nth-qubit of a n-qubits state\n
    Raise:\n
        ValueError if number of qubits is less than 1\n
        ValueError if qubit position is < 0 or > n_qubits-1 """
    if n_qubits < 1:
        raise ValueError('number of vertices must be > 0, but is {}'.format(n_qubits))
    if qubit_pos < 0 or qubit_pos > n_qubits-1:
        raise ValueError('number of vertices must be > 0 or <= n_qubits, but is {}'.format(qubit_pos))
    n_sigmax = []
    for i in range(n_qubits):
        n_sigmax.append(qu.tensor([qu.qeye(2)]*i+[qu.sigmax()]+[qu.qeye(2)]*(n_qubits-i-1)))
    return n_sigmax[qubit_pos]

In [175]:
gen_state.proj()

Quantum object: dims = [[2, 2, 2], [2, 2, 2]], shape = (8, 8), type = oper, isherm = True
Qobj data =
[[0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.63098714 0.04628083 0.         0.
  0.47902608 0.03513499]
 [0.         0.         0.04628083 0.00339455 0.         0.
  0.03513499 0.00257704]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.47902608 0.03513499 0.         0.
  0.36366191 0.0266734 ]
 [0.         0.         0.03513499 0.00257704 0.         0.
  0.0266734  0.00195641]]

In [265]:
list_gen_state = []
i = 0
coeffs = np.random.random((2,n_qubits))
basis_elem = np.random.randint(0,2,(2,n_qubits))
while i < n_qubits:
    gen_qubit = (coeffs[0][i]*qu.basis(2,basis_elem[0][i]) + coeffs[1][i]*qu.basis(2,basis_elem[1][i])).unit()
    list_gen_state.append(gen_qubit)
    i += 1
gen_state2 = qu.tensor(list_gen_state)

In [259]:
list_gen_state2 = []
for i in range(n_qubits):
    tr_coeff = 
    list_gen_state2.append(gen_state2.ptrace(i))
exp2 = qu.tensor(list_gen_state2)

In [260]:
gen_state2 == exp2

False

In [289]:
#generate a generic n-qubits state
n_qubits=3
dimensions = [[],[]]
for vertex in range(n_qubits):
    dimensions[0].append(2)
    dimensions[1].append(1) 
gen_state = qu.rand_ket(2**n_qubits,dims=dimensions).unit()

In [290]:
list_gen_state2 = []
for i in range(n_qubits):
    list_gen_state2.append(gen_state.ptrace(i))
exp = qu.tensor(list_gen_state2)

In [293]:
exp

Quantum object: dims = [[2, 2, 2], [2, 2, 2]], shape = (8, 8), type = oper, isherm = True
Qobj data =
[[ 0.23801219+0.j          0.09228891+0.10520975j -0.07447478-0.10720549j
   0.01851109-0.07448925j  0.0898449 -0.06690733j  0.06441263+0.01377137j
  -0.05824917-0.01953243j -0.01395202-0.03332185j]
 [ 0.09228891-0.10520975j  0.1686835 +0.j         -0.07626609-0.00864832j
  -0.05278161-0.07597845j  0.00526185-0.06565783j  0.06367469-0.04741843j
  -0.03122006+0.0181745j  -0.04128223-0.01384299j]
 [-0.07447478+0.10720549j -0.07626609+0.00864832j  0.14851946+0.j
   0.05758823+0.06565082j  0.00202365+0.06140347j -0.02635782+0.02470364j
   0.05606316-0.04175014j  0.04019344+0.00859333j]
 [ 0.01851109+0.07448925j -0.05278161+0.07597845j  0.05758823-0.06565082j
   0.10525841+0.j          0.02792716+0.02291459j  0.0014342 +0.04351774j
   0.00328339-0.04097045j  0.03973297-0.02958907j]
 [ 0.0898449 +0.06690733j  0.00526185+0.06565783j  0.00202365-0.06140347j
   0.02792716-0.02291459j  0.1223537

In [294]:
qu.ket2dm(gen_state)

Quantum object: dims = [[2, 2, 2], [2, 2, 2]], shape = (8, 8), type = oper, isherm = True
Qobj data =
[[ 0.28354282+0.j          0.1895494 +0.12313804j -0.11883844-0.03890043j
   0.03439098-0.1973968j   0.09802436-0.1204873j   0.09690838-0.09792708j
  -0.20787269-0.05069079j  0.07770201-0.03667635j]
 [ 0.1895494 -0.12313804j  0.18019131+0.j         -0.09633775+0.02560453j
  -0.06273573-0.14689591j  0.01320396-0.12311659j  0.02225546-0.10755035j
  -0.16097783+0.05638876j  0.03601613-0.058263j  ]
 [-0.11883844+0.03890043j -0.09633775-0.02560453j  0.05514447+0.j
   0.01266775+0.08745117j -0.0245538 +0.063947j   -0.0271812 +0.05433846j
   0.09407807-0.00727341j -0.02753468+0.02603206j]
 [ 0.03439098+0.1973968j  -0.06273573+0.14689591j  0.01266775-0.08745117j
   0.14159496+0.j          0.09577023+0.05362865j  0.0799289 +0.05558806j
   0.01007698-0.15086508j  0.03495783+0.04964609j]
 [ 0.09802436+0.1204873j   0.01320396+0.12311659j -0.0245538 -0.063947j
   0.09577023-0.05362865j  0.08508756+

In [291]:
qu.ket2dm(gen_state) == exp

False

In [337]:
psi = qu.tensor(qu.basis(2,0),qu.basis(2,1))

In [391]:
n_qubits=2
dimensions = [[],[]]
for vertex in range(n_qubits):
    dimensions[0].append(2)
    dimensions[1].append(1) 
psi = qu.rand_ket(2**n_qubits,dims=dimensions).unit()
psi_dm = qu.rand_dm_hs(2**n_qubits, dims=[[2] * 2] * 2)

In [377]:
psi

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[-0.26708017+0.12370213j]
 [ 0.27711714-0.41533443j]
 [ 0.65008193-0.46492925j]
 [ 0.07729101+0.1390314j ]]

In [387]:
qu.ket2dm(psi)

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 0.30543952+0.j         -0.2857862 -0.06148607j -0.24846663-0.24979845j
  -0.05028638-0.00531798j]
 [-0.2857862 +0.06148607j  0.27977483+0.j          0.28276452+0.1837081j
   0.04812126-0.00514703j]
 [-0.24846663+0.24979845j  0.28276452-0.1837081j   0.4064141 +0.j
   0.0452558 -0.03679982j]
 [-0.05028638+0.00531798j  0.04812126+0.00514703j  0.0452558 +0.03679982j
   0.00837155+0.j        ]]

In [392]:
psi_dm

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 0.16259642+1.43869592e-18j  0.10454146+8.44836115e-02j
   0.04884094+8.91291466e-03j -0.01620836+5.28517186e-02j]
 [ 0.10454146-8.44836115e-02j  0.36578523-1.20819691e-19j
   0.09233406+1.16182655e-01j  0.13976686+2.18805393e-01j]
 [ 0.04884094-8.91291466e-03j  0.09233406-1.16182655e-01j
   0.16485679-3.97822585e-18j  0.14458306-2.42210771e-02j]
 [-0.01620836-5.28517186e-02j  0.13976686-2.18805393e-01j
   0.14458306+2.42210771e-02j  0.30676156+2.66034962e-18j]]

In [394]:
qu.tensor(psi_dm.ptrace(0),psi_dm.ptrace(1))

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0.17302026+0.j         0.13163282+0.03184162j 0.06176023+0.07456709j
  0.03326394+0.0680962j ]
 [0.13163282-0.03184162j 0.35536138+0.j         0.06070971+0.04536423j
  0.12684757+0.15315122j]
 [0.06176023-0.07456709j 0.06070971-0.04536423j 0.15443294+0.j
  0.11749169+0.02842092j]
 [0.03326394-0.0680962j  0.12684757-0.15315122j 0.11749169-0.02842092j
  0.31718541+0.j        ]]

In [393]:
psi_dm==qu.tensor(psi_dm.ptrace(0),psi_dm.ptrace(1))

False

In [378]:
qu.ket2dm(psi).tr()

1.0

In [379]:
psi.ptrace(0)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 0.33593064+4.79807669e-18j -0.2674626 -1.14386469e-01j]
 [-0.2674626 +1.14386469e-01j  0.66406936+2.00967138e-17j]]

In [380]:
psi.ptrace(1)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 0.72539977-1.95807375e-17j -0.13978452-2.02964264e-01j]
 [-0.13978452+2.02964264e-01j  0.27460023-5.31405299e-18j]]

In [381]:
qu.ket2dm(psi)==qu.tensor(psi.ptrace(0),psi.ptrace(1))

False

In [292]:
gen_state

Quantum object: dims = [[2, 2, 2], [1, 1, 1]], shape = (8, 1), type = ket
Qobj data =
[[-0.45048203-0.28391681j]
 [-0.42444933+0.00583762j]
 [ 0.22775773+0.05719167j]
 [ 0.14301809-0.34805285j]
 [-0.03509115-0.28957929j]
 [-0.05590809-0.25261902j]
 [ 0.38101787+0.12761128j]
 [-0.08672527-0.1360745j ]]

In [286]:
round(qu.ket2dm(gen_state).tr(),15)

1.0

In [287]:
round(gen_state.ptrace(1).tr(),15)

1.0

In [285]:
int(0.9)

0

In [227]:
obs = (n_sigmax(n_qubits,1)*gen_state).proj()

In [228]:
qu.sigmax()*gen_state.ptrace(1)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[-0.02796117+0.31052402j  0.54629355+0.j        ]
 [ 0.45370645+0.j         -0.02796117-0.31052402j]]

In [229]:
qubit_pos = 1
list_gen_state2 = []
for i in range(n_qubits):
    if i == qubit_pos:
        list_gen_state2.append(qu.sigmax()*gen_state.ptrace(i)*qu.sigmax().dag())
    else:
        list_gen_state2.append(gen_state.ptrace(i))
exp = qu.tensor(list_gen_state2)

In [230]:
exp == obs

False

In [ ]:
#generate a generic n-qubits state
    dimensions = [[],[]]
    for vertex in range(n_qubits):
        dimensions[0].append(2)
        dimensions[1].append(1) 
    gen_state = qu.rand_ket(2**n_qubits,dims=dimensions)
    #Test if n_sigmax apply sigmax on qubit in qubit_pos
    qubit_pos = np.random.randint(0,n_qubits)
    list_gen_state = []
    for i in range(n_qubits):
        if i == qubit_pos:
            list_gen_state.append(qu.sigmax()*gen_state.ptrace(i)*qu.sigmax().dag())
        else:
            list_gen_state.append(gen_state.ptrace(i))
    exp = qu.tensor(list_gen_state)
    obs = (qaoa.n_sigmax(n_qubits, qubit_pos)*gen_state).proj()
    assert_equal(exp, obs)

In [138]:
qu.sigmax()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 1.]
 [1. 0.]]

In [199]:
qubit_pos = np.random.randint(0,n_qubits)

In [201]:
type(qubit_pos)

int

In [145]:
n_sigmax(n_qubits,2)*gen_state

Quantum object: dims = [[2, 2, 2], [1, 1, 1]], shape = (8, 1), type = ket
Qobj data =
[[0.        ]
 [0.        ]
 [0.05826274]
 [0.79434699]
 [0.        ]
 [0.        ]
 [0.04423128]
 [0.60304387]]

In [157]:
qu.rand_ket()

Quantum object: dims = [[3], [1]], shape = (3, 1), type = ket
Qobj data =
[[-0.03338462+0.55793145j]
 [ 0.16460371+0.5913793j ]
 [ 0.25716163-0.49461298j]]

In [153]:
gen_state.ptrace(2).extract_states(0)

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[0.99464905]]

In [ ]:
list_gen_state

In [155]:
gen_state.full()

array([[0.        +0.j],
       [0.        +0.j],
       [0.79434699+0.j],
       [0.05826274+0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.60304387+0.j],
       [0.04423128+0.j]])

In [164]:
qu.sigmax()*qu.sigmax()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 1.]]

In [163]:
type(qu.sigmax())

qutip.qobj.Qobj

In [161]:
gen_state.ptrace(1)*qu.sigmax

TypeError: unsupported operand type(s) for *: 'Qobj' and 'function'

In [ ]:
#generate a generic n-qubits state
    #gen_state = qaoa.generic_state(n_qubits)
    #Test if n_sigmax apply sigmax on qubit in qubit_pos
    qubit_pos = np.random.randint(0,n_qubits)
    list_gen_state = []
    for i in range(n_qubits):
        if i == qubit_pos:
            list_gen_state.append(qu.sigmax()*gen_state.ptrace(i))
        else:
            list_gen_state.append(gen_state.ptrace(i))
    exp = qu.tensor(list_gen_state)
    obs = (qaoa.n_sigmax(n_qubits, qubit_pos)*gen_state).proj()

In [207]:
#generate a generic n-qubits state
dimensions = [[],[]]
for vertex in range(n_qubits):
    dimensions[0].append(2)
    dimensions[1].append(1) 
gen_state = qu.rand_ket(2**n_qubits,dims=dimensions)

In [224]:
gen_state

Quantum object: dims = [[2, 2, 2], [1, 1, 1]], shape = (8, 1), type = ket
Qobj data =
[[0.99381016]
 [0.        ]
 [0.11109174]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]]

In [212]:
gen_state.proj()

Quantum object: dims = [[2, 2, 2], [2, 2, 2]], shape = (8, 8), type = oper, isherm = True
Qobj data =
[[ 0.27012363+0.j          0.26657228+0.03419253j  0.05268398+0.17240408j
  -0.13899752+0.09282947j  0.07907092+0.07947857j -0.11651791+0.0744056j
  -0.16283462+0.06054367j -0.00346176+0.05114933j]
 [ 0.26657228-0.03419253j  0.26739574+0.j          0.07381442+0.16346866j
  -0.12541965+0.10920347j  0.08809184+0.06842477j -0.1055677 +0.08817634j
  -0.15303013+0.08035946j  0.00305828+0.05091506j]
 [ 0.05268398-0.17240408j  0.07381442-0.16346866j  0.12031072+0.j
   0.03213801+0.10681911j  0.06614823-0.03496511j  0.02476348+0.08887837j
   0.00688277+0.11573602j  0.03197045+0.01218543j]
 [-0.13899752-0.09282947j -0.12541965-0.10920347j  0.03213801-0.10681911j
   0.10342531+0.j         -0.01337428-0.06807044j  0.08552652+0.00175513j
   0.10459598+0.02480505j  0.01935907-0.02513026j]
 [ 0.07907092-0.07947857j  0.08809184-0.06842477j  0.06614823+0.03496511j
  -0.01337428+0.06807044j  0.04653074

In [232]:
#Test if n_sigmax apply sigmax on qubit in qubit_pos
qubit_pos = np.random.randint(0,n_qubits)
list_gen_state = []
for i in range(n_qubits):
    if i == qubit_pos:
        list_gen_state.append(qu.sigmax().dag()*gen_state.ptrace(i)*qu.sigmax())
    else:
        list_gen_state.append(gen_state.ptrace(i))
exp = qu.tensor(list_gen_state)
obs = (n_sigmax(n_qubits, qubit_pos)*gen_state).proj()

In [269]:
obs = (n_sigmax(n_qubits,1)*gen_state).proj()

In [272]:
qubit_pos=1
list_gen_state2 = []
for i in range(n_qubits):
    if i == qubit_pos:
        list_gen_state2.append(qu.sigmax()*gen_state.ptrace(i)*qu.sigmax().dag())
    else:
        list_gen_state2.append(gen_state.ptrace(i))
exp = qu.tensor(list_gen_state2)

In [273]:
obs == exp

True

In [234]:
exp

Quantum object: dims = [[2, 2, 2], [2, 2, 2]], shape = (8, 8), type = oper, isherm = True
Qobj data =
[[ 0.09810868+0.j          0.01584193+0.01107268j -0.00604627-0.06714716j
   0.00660201-0.01152486j -0.04104105-0.01452153j -0.00498811-0.00697679j
  -0.00740948+0.02898409j -0.00446762+0.00384391j]
 [ 0.01584193-0.01107268j  0.11178923+0.j         -0.00855463-0.01016008j
  -0.00688938-0.07651035j -0.00826595+0.00228711j -0.04676393-0.01654645j
   0.00207475+0.0055164j  -0.00844267+0.03302572j]
 [-0.00604627+0.06714716j -0.00855463+0.01016008j  0.11812955+0.j
   0.01907476+0.01333226j  0.01246806-0.02719422j  0.00508243-0.00298398j
  -0.04941623-0.01748491j -0.00600603-0.00840053j]
 [ 0.00660201+0.01152486j -0.00688938+0.07651035j  0.01907476-0.01333226j
   0.13460187+0.j         -0.00105592-0.0057983j   0.01420664-0.03098626j
  -0.00995277+0.00275384j -0.05630696-0.01992306j]
 [-0.04104105+0.01452153j -0.00826595-0.00228711j  0.01246806+0.02719422j
  -0.00105592+0.0057983j   0.1139588

In [238]:
obs

Quantum object: dims = [[2, 2, 2], [2, 2, 2]], shape = (8, 8), type = oper, isherm = True
Qobj data =
[[ 0.13761422+0.j         -0.13781711-0.09049723j  0.11621027-0.00707554j
   0.11095076-0.044316j    0.09469933+0.01817696j  0.09007403+0.10791241j
  -0.03190687+0.14667475j -0.10888212+0.01485748j]
 [-0.13781711+0.09049723j  0.19753267+0.j         -0.11172862+0.08350763j
  -0.08197144+0.11734427j -0.10679239+0.04407198j -0.16117169-0.04883744j
  -0.06450167-0.16787344j  0.09927215-0.08648195j]
 [ 0.11621027+0.00707554j -0.11172862-0.08350763j  0.09849919+0.j
   0.09597247-0.03171866j  0.0790356 +0.02021883j  0.07051589+0.09575938j
  -0.0344856 +0.12222104j -0.09271095+0.00694835j]
 [ 0.11095076+0.044316j   -0.08197144-0.11734427j  0.09597247+0.03171866j
   0.10372459+0.j          0.07049731+0.04515117j  0.03787061+0.11601043j
  -0.07295852+0.10798077j -0.09257022-0.02308462j]
 [ 0.09469933-0.01817696j -0.10679239-0.04407198j  0.0790356 -0.02021883j
   0.07049731-0.04515117j  0.0675683

In [205]:
from nose.tools import assert_equal

def test_n_sigmax(n_qubits):
    #generate a generic n-qubits state
    dimensions = [[],[]]
    for vertex in range(n_qubits):
        dimensions[0].append(2)
        dimensions[1].append(1) 
    gen_state = qu.rand_ket(2**n_qubits,dims=dimensions)
    #Test if n_sigmax apply sigmax on qubit in qubit_pos
    qubit_pos = np.random.randint(0,n_qubits)
    list_gen_state = []
    for i in range(n_qubits):
        if i == qubit_pos:
            list_gen_state.append(qu.sigmax()*gen_state.ptrace(i)*qu.sigmax().dag())
        else:
            list_gen_state.append(gen_state.ptrace(i))
    exp = qu.tensor(list_gen_state)
    obs = (n_sigmax(n_qubits, qubit_pos)*gen_state).proj()
    assert_equal(exp, obs)

In [206]:
test_n_sigmax(n_qubits)

AssertionError: Quant[98 chars][ 0.07582434+0.j          0.00999775+0.0140547[1521 chars]   ]] != Quant[98 chars][ 0.09936924+0.j         -0.01371488+0.0418552[1520 chars]   ]]

In [400]:
def generic_state(n_qubits):
    """This method initialize the a genric n-qubits state\n
    Parameters:\n
        n_qubits: number of qubits the states is composed of\n
    Returns:\n
        an object of the Qobj class defined in qutip, tensor of n-qubits\n
    Raise:\n
        ValueError if number of qubits is less than 1"""
    list_gen_state = []
    i = 0
    coeffs_real = np.random.random((2,n_qubits))
    coeffs_imm = np.random.random((2,n_qubits))
    basis_elem = np.random.randint(0,2,(2,n_qubits))
    while i < n_qubits:
        gen_qubit = (complex(coeffs_real[0][i],coeffs_imm[0][i])*qu.basis(2,basis_elem[0][i])
                     + complex(coeffs_real[1][i],coeffs_imm[1][i])*qu.basis(2,basis_elem[1][i])).unit()
        list_gen_state.append(gen_qubit)
        i += 1
    gen_state = qu.tensor(list_gen_state)
    return gen_state

In [409]:
n_qubits=3
list_gen_state = []
i = 0
coeffs_real = np.random.random((2,n_qubits))
coeffs_imm = np.random.random((2,n_qubits))
basis_elem = np.random.randint(0,2,(2,n_qubits))
while i < n_qubits:
    gen_qubit = (complex(coeffs_real[0][i],coeffs_imm[0][i])*qu.basis(2,basis_elem[0][i])
                 + complex(coeffs_real[1][i],coeffs_imm[1][i])*qu.basis(2,basis_elem[1][i])).unit()
    list_gen_state.append(gen_qubit)
    i += 1
gen_state = qu.tensor(list_gen_state)

In [410]:
list_gen_state

[Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
 Qobj data =
 [[0.48584331+0.62578689j]
  [0.60985026+0.02072931j]],
 Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
 Qobj data =
 [[0.        +0.j        ]
  [0.76006061+0.64985219j]],
 Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
 Qobj data =
 [[0.        +0.j        ]
  [0.43373806+0.90103901j]]]

In [411]:
qubit_pos=1
obs = n_sigmax(n_qubits,qubit_pos)*gen_state

In [414]:
list_exp = []
for i in range(n_qubits):
    if i == qubit_pos:
        list_exp.append(qu.sigmax()*list_gen_state[i])
    else:
        list_exp.append(list_gen_state[i])
exp = qu.tensor(list_exp)

In [415]:
exp == obs

True

In [ ]:
@given(n_qubits=st.integers(1,5))
@settings(deadline=None)
def test_generic_state(n_qubits):
    #Initialazing a generic n-qubits state
    state = qaoa.generic_state(n_qubits) 
    #Test if the shape of the state is (2**n_qubits,1)
    exp = (2**n_qubits,1)
    obs = state.shape
    assert_equal(exp,obs)
    #Test if the dims of the state are of a n_vertices qubits
    exp = [[],[]]
    for vertex in range(n_qubits):
        exp[0].append(2)
        exp[1].append(1)
    obs = state.dims
    assert_equal(exp,obs)
    #Test if the dims of the state are of a n_qubits state
    exp = [[],[]]
    vertex = 0
    while vertex < n_qubits:
        exp[0].append(2)
        exp[1].append(1)
        vertex += 1
    obs = state.dims
    assert_equal(exp,obs)
    #Test if the state is a ket
    exp = 'ket'
    obs = state.type
    assert_equal(exp,obs)